-- begin PRACTIC_SHOP
alter table PRACTIC_SHOP add constraint FK_PRACTIC_SHOP_ON_BRAND foreign key (BRAND_ID) references PRACTIC_BRAND(ID)^
create unique index IDX_PRACTIC_SHOP_UK_SHOP_ID on PRACTIC_SHOP (SHOP_ID) where DELETE_TS is null ^
create index IDX_PRACTIC_SHOP_ON_BRAND on PRACTIC_SHOP (BRAND_ID)^
-- end PRACTIC_SHOP
-- begin PRACTIC_FABRIC
alter table PRACTIC_FABRIC add constraint FK_PRACTIC_FABRIC_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create unique index IDX_PRACTIC_FABRIC_UK_NAME_FABRIC_ID on PRACTIC_FABRIC (NAME_FABRIC_ID) where DELETE_TS is null ^
create index IDX_PRACTIC_FABRIC_ON_USER on PRACTIC_FABRIC (USER_ID)^
-- end PRACTIC_FABRIC
-- begin PRACTIC_PRODUCT
alter table PRACTIC_PRODUCT add constraint FK_PRACTIC_PRODUCT_ON_FABRIC foreign key (FABRIC_ID) references PRACTIC_FABRIC(ID)^
create unique index IDX_PRACTIC_PRODUCT_UK_PRODUCT_NAME on PRACTIC_PRODUCT (PRODUCT_NAME) where DELETE_TS is null ^
create index IDX_PRACTIC_PRODUCT_ON_FABRIC on PRACTIC_PRODUCT (FABRIC_ID)^
-- end PRACTIC_PRODUCT
-- begin PRACTIC_BRAND
create unique index IDX_PRACTIC_BRAND_UK_NAME on PRACTIC_BRAND (NAME) where DELETE_TS is null ^
-- end PRACTIC_BRAND
